--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Ifera/ScoreHud
branches:
- master
projects:
  ScoreHud:
    icon: meta/ScoreHud.PNG
    libs:
      - src: buchwasa/ScoreFactory/ScoreFactory
        version: ^4.0.0
        branch: pm4
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ^2.0.0
        branch: API-4.0.0
      - src: Ifera/ConfigUpdater/ConfigUpdater
        version: ^1.1.0
    lint:
      phpstan: false
...
