--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Ifera/ScoreHud
branches:
- master
projects:
  ScoreHud:
    icon: meta/ScoreHud.PNG
    libs:
      - src: stephen-mc-pl/ScoreFactory/ScoreFactory
        version: ^1.0.0
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: ^2.0.0
      - src: Ifera/ConfigUpdater
        version: ^1.0.0
    lint:
      phpstan: false
...
