--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JackMD/ScoreHud
branches:
- master
projects:
  ScoreHud:
    icon: meta/ScoreHud.PNG
    libs:
      - src: JackMD/ScoreFactory/ScoreFactory
        version: ^1.0.0
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: ^1.0.0
...
