name: ScoreHud
main: Ifera\ScoreHud\ScoreHud
api: [3.0.0]
version: 6.0.1
author: JackMD
description: Add fully customizable scoreboards to your server.

virions:
- ScoreFactory
- UpdateNotifier
- ConfigUpdater

permissions:
  sh.command.sh:
    default: true
    description: Allow players to use /scorehud command.
