name: ScoreHud
main: Ifera\ScoreHud\ScoreHud
api: 5.0.0
version: 8.0.0
author: Ifera
description: Add fully customizable scoreboards to your server.

virions:
- ScoreFactory
- UpdateNotifier
- ConfigUpdater

permissions:
  sh.command.sh:
    default: true
    description: Allow players to use /scorehud command.
